/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TurnReturnRouteImport } from './routes/turn-return'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PreviewRoomCodeRouteImport } from './routes/preview-room-code'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OfflineIndexRouteImport } from './routes/offline/index'
import { Route as RoomRoomIdRouteImport } from './routes/room/$roomId'

const TurnReturnRoute = TurnReturnRouteImport.update({
  id: '/turn-return',
  path: '/turn-return',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoomCodeRoute = PreviewRoomCodeRouteImport.update({
  id: '/preview-room-code',
  path: '/preview-room-code',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineIndexRoute = OfflineIndexRouteImport.update({
  id: '/offline/',
  path: '/offline/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/preview-room-code': typeof PreviewRoomCodeRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/turn-return': typeof TurnReturnRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/offline/': typeof OfflineIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/preview-room-code': typeof PreviewRoomCodeRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/turn-return': typeof TurnReturnRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/offline': typeof OfflineIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/preview-room-code': typeof PreviewRoomCodeRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/turn-return': typeof TurnReturnRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/offline/': typeof OfflineIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/preview-room-code'
    | '/privacy'
    | '/profile'
    | '/turn-return'
    | '/room/$roomId'
    | '/offline/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/preview-room-code'
    | '/privacy'
    | '/profile'
    | '/turn-return'
    | '/room/$roomId'
    | '/offline'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/preview-room-code'
    | '/privacy'
    | '/profile'
    | '/turn-return'
    | '/room/$roomId'
    | '/offline/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  PreviewRoomCodeRoute: typeof PreviewRoomCodeRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  TurnReturnRoute: typeof TurnReturnRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
  OfflineIndexRoute: typeof OfflineIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/turn-return': {
      id: '/turn-return'
      path: '/turn-return'
      fullPath: '/turn-return'
      preLoaderRoute: typeof TurnReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-room-code': {
      id: '/preview-room-code'
      path: '/preview-room-code'
      fullPath: '/preview-room-code'
      preLoaderRoute: typeof PreviewRoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline/': {
      id: '/offline/'
      path: '/offline'
      fullPath: '/offline/'
      preLoaderRoute: typeof OfflineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  PreviewRoomCodeRoute: PreviewRoomCodeRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  TurnReturnRoute: TurnReturnRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
  OfflineIndexRoute: OfflineIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
